services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: threaded
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 -uroot -p1234 --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: ghcr.io/gamingarmorydev2nd/threaded-backend:v1.0.0
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/threaded?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"